[package]
name = "sparsdr_bin_mask"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]

[dependencies]

# Benchmarking section
[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "micro"
harness = false
